export const TH_TEXT = {
  app: {
    name: "Walpaca",
    metadataTitle: "Walpaca | จัดการเงินส่วนตัว",
    metadataDescription: "แอปจัดการการเงินส่วนตัว",
    tagline: "จัดการเงินส่วนตัว",
    mainNavigation: "เมนูหลัก",
    appearance: "ธีม",
    appearanceHint: "สว่างหรือมืด",
  },
  navigation: {
    dashboard: "แดชบอร์ด",
    wallet: "กระเป๋าเงิน",
    transactions: "รายการ",
    transfer: "โอนเงิน",
    profile: "โปรไฟล์",
  },
  common: {
    create: "สร้าง",
    edit: "แก้ไข",
    delete: "ลบ",
    save: "บันทึก",
    cancel: "ยกเลิก",
    close: "ปิด",
    none: "ไม่มี",
    active: "ใช้งานอยู่",
    inactive: "ปิดใช้งาน",
    created: "วันที่สร้าง",
    updated: "อัปเดตล่าสุด",
    status: "สถานะ",
    color: "สี",
    description: "รายละเอียด",
    optionalNote: "บันทึกเพิ่มเติม",
  },
  dashboard: {
    metadataTitle: "แดชบอร์ด | Walpaca",
    metadataDescription: "ภาพรวมการเงินส่วนตัวของคุณ",
    eyebrow: "ภาพรวม",
    title: "แดชบอร์ด",
    subtitle: "ดูภาพรวมยอดเงิน รายจ่าย และข้อมูลสำคัญแบบเข้าใจง่าย",
    totalBalance: "ยอดเงินรวม",
    monthlySpending: "รายจ่ายเดือนนี้",
    activeWallets: "กระเป๋าที่ใช้งาน",
    zeroBaht: "0 บาท",
    comingTitle: "แดชบอร์ดกำลังจะพร้อมใช้งาน",
    comingDescription: "พื้นที่นี้เตรียมไว้สำหรับกราฟ สรุปภาพรวม และรายการล่าสุดเมื่อเชื่อมต่อข้อมูลจริงแล้ว",
  },
  wallet: {
    metadataTitle: "กระเป๋าเงิน | Walpaca",
    metadataDescription: "จัดการกระเป๋าเงินและกระเป๋าย่อยใน Walpaca",
    eyebrow: "โครงสร้าง",
    title: "กระเป๋าเงิน",
    subtitle: "จัดการกระเป๋าหลัก กระเป๋าย่อย และบัญชีลงทุนในที่เดียว",
    newWallet: "สร้างกระเป๋า",
    createWallet: "สร้างกระเป๋า",
    editWallet: "แก้ไขกระเป๋า",
    createSubWallet: "สร้างกระเป๋าย่อย",
    addSubWallet: "เพิ่มกระเป๋าย่อย",
    walletTree: "โครงสร้างกระเป๋า",
    treeHint: "จัดเงินตามเป้าหมาย",
    noWalletsTitle: "ยังไม่มีกระเป๋า",
    noWalletsDescription: "สร้างกระเป๋าแรกเพื่อเริ่มจัดกลุ่มเงินออม เงินใช้จ่าย หรือเงินลงทุน",
    noWalletSelectedTitle: "ยังไม่ได้เลือกกระเป๋า",
    noWalletSelectedDescription: "เลือกกระเป๋าจากรายการ หรือสร้างกระเป๋าใหม่เพื่อเริ่มจัดโครงสร้างการเงิน",
    noDescription: "ไม่มีรายละเอียด",
    balance: "ยอดเงิน",
    type: "ประเภท",
    normal: "ทั่วไป",
    investment: "ลงทุน",
    subWallets: "กระเป๋าย่อย",
    currency: "สกุลเงิน",
    walletName: "ชื่อกระเป๋า",
    walletNamePlaceholder: "เงินออม",
    walletNameRequired: "กรุณากรอกชื่อกระเป๋า",
    parent: "กระเป๋าหลัก",
    modalHint: "กรอกเฉพาะข้อมูลสำคัญเพื่อให้จัดการง่าย",
    saveChanges: "บันทึกการแก้ไข",
    collapseWallet: "ยุบกระเป๋า",
    expandWallet: "ขยายกระเป๋า",
    addSubWalletTo: "เพิ่มกระเป๋าย่อยใน",
    useColor: "ใช้สี",
    deleteConfirmTitle: "ลบกระเป๋า?",
    deleteConfirmMessage: "คุณต้องการลบ \"%s\" หรือไม่? การดำเนินการนี้ไม่สามารถย้อนกลับได้",
  },
  profile: {
    metadataTitle: "โปรไฟล์ | Walpaca",
    metadataDescription: "จัดการโปรไฟล์ Walpaca ของคุณ",
    eyebrow: "บัญชี",
    title: "โปรไฟล์",
    subtitle: "จัดการข้อมูลบัญชีและข้อมูลส่วนตัวของคุณ",
    fullName: "ชื่อ-นามสกุล",
    email: "อีเมล",
    displayName: "ผู้ใช้ Walpaca",
    displayEmail: "user@example.com",
    editProfile: "แก้ไขโปรไฟล์",
    updateProfile: "อัปเดตโปรไฟล์",
  },
  auth: {
    username: "ชื่อผู้ใช้",
    email: "อีเมล",
    password: "รหัสผ่าน",
    confirmPassword: "ยืนยันรหัสผ่าน",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    usernameRequired: "กรุณากรอกชื่อผู้ใช้",
    usernameMinLength: "ชื่อผู้ใช้ต้องมีอย่างน้อย 3 ตัวอักษร",
    usernamePattern: "ชื่อผู้ใช้ใช้ได้เฉพาะ a-z, 0-9 และ _",
    emailRequired: "กรุณากรอกอีเมล",
    emailInvalid: "รูปแบบอีเมลไม่ถูกต้อง",
    passwordRequired: "กรุณากรอกรหัสผ่าน",
    passwordMinLength: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    passwordPattern: "รหัสผ่านต้องมีตัวพิมพ์เล็กและพิมพ์ใหญ่อย่างน้อย 1 ตัว",
    confirmPasswordRequired: "กรุณายืนยันรหัสผ่าน",
    passwordMismatch: "รหัสผ่านไม่ตรงกัน",
  },
  transaction: {
    metadataTitle: "รายการธุรกรรม | Walpaca",
    metadataDescription: "จัดการรายการธุรกรรมทั้งหมด",
    eyebrow: "ธุรกรรม",
    title: "รายการธุรกรรม",
    subtitle: "ดูและจัดการรายการทั้งหมดของคุณ",
    addTransaction: "เพิ่มรายการ",
    name: "ชื่อรายการ",
    namePlaceholder: "เช่น ค่าอาหาร",
    nameRequired: "กรุณากรอกชื่อรายการ",
    amount: "จำนวนเงิน",
    amountPlaceholder: "0.00",
    amountRequired: "กรุณากรอกจำนวนเงิน",
    type: "ประเภท",
    income: "รายรับ",
    expense: "รายจ่าย",
    category: "หมวดหมู่",
    selectCategory: "เลือกหมวดหมู่",
    date: "วันที่",
    note: "หมายเหตุ",
    notePlaceholder: "บันทึกเพิ่มเติม (ไม่บังคับ)",
    wallet: "กระเป๋า",
    allWallets: "ทุกกระเป๋า",
    allTypes: "ทุกประเภท",
    allCategories: "ทุกหมวดหมู่",
    filter: "ตัวกรอง",
    search: "ค้นหา",
    searchPlaceholder: "ค้นหารายการ...",
    loadMore: "โหลดเพิ่มเติม",
    showMore: "แสดงเพิ่มเติม",
    editTransaction: "แก้ไขรายการ",
    deleteSelected: "ลบรายการ",
    noTransactions: "ยังไม่มีรายการ",
    noTransactionsDescription: "เพิ่มรายการแรกของคุณ",
    overview: "ภาพรวม",
    transactions: "รายการ",
    created: "สร้างเมื่อ",
  },
  transfer: {
    metadataTitle: "โอนเงิน | Walpaca",
    metadataDescription: "ย้ายเงินระหว่างกระเป๋าใน Walpaca",
    eyebrow: "การย้ายเงิน",
    title: "โอนเงิน",
    subtitle: "ย้ายเงินจากกระเป๋าต้นทางไปยังกระเป๋าปลายทาง",
    sourceWallet: "กระเป๋าต้นทาง",
    destinationWallet: "กระเป๋าปลายทาง",
    transferTo: "ไปยัง",
    amount: "จำนวนเงิน",
    date: "วันที่โอน",
    note: "หมายเหตุ",
    submit: "โอนเงิน",
    saving: "กำลังโอนเงิน",
    editTitle: "แก้ไขรายการโอนเงิน",
    editDescription: "ปรับข้อมูลรายการโอนเงินเดิม ระบบจะอัปเดตรายการคู่ให้อัตโนมัติ",
    saveChanges: "บันทึกการแก้ไข",
    savingChanges: "กำลังบันทึก",
    cancelEdit: "ยกเลิกการแก้ไข",
    formDescription: "เลือกกระเป๋าต้นทาง ปลายทาง และจำนวนเงินที่ต้องการย้าย",
    historyTitle: "ประวัติการโอนเงิน",
    historyDescription: "รายการโอนเงินย้อนหลังที่สามารถแก้ไขหรือลบได้",
    historyEmptyTitle: "ยังไม่มีประวัติการโอนเงิน",
    historyEmptyDescription: "เมื่อโอนเงินสำเร็จ รายการจะแสดงที่นี่เพื่อให้ตรวจสอบและแก้ไขย้อนหลัง",
    historyLoading: "กำลังโหลดประวัติการโอนเงิน",
    historyActions: "จัดการ",
    deleteConfirmTitle: "ลบรายการโอนเงิน?",
    deleteConfirmMessage: "คุณต้องการลบรายการโอนเงิน \"%s\" หรือไม่? ระบบจะคืนยอดเงินกลับไปยังกระเป๋าต้นทาง",
    previewTitle: "ตรวจสอบยอดเงิน",
    previewDescription: "ดูยอดเงินก่อนและหลังโอนเพื่อยืนยันความถูกต้อง",
    currentBalance: "ยอดปัจจุบัน",
    afterTransfer: "หลังโอน",
    selectSourceWallet: "เลือกกระเป๋าต้นทาง",
    selectDestinationWallet: "เลือกกระเป๋าปลายทาง",
    swapWallets: "สลับกระเป๋าต้นทางและปลายทาง",
    submitHint: "กรอกข้อมูลให้ครบและตรวจสอบยอดเงินก่อนโอน",
    noWalletsTitle: "ต้องมีกระเป๋าอย่างน้อย 2 ใบ",
    noWalletsDescription: "สร้างหรือจัดการกระเป๋าเงินก่อน เพื่อเลือกกระเป๋าต้นทางและปลายทางสำหรับการโอน",
    manageWallets: "ไปจัดการกระเป๋าเงิน",
    walletSummary: "สรุปกระเป๋าเงิน",
    loadFailed: "โหลดรายการโอนเงินไม่สำเร็จ",
    loadOneFailed: "โหลดรายการโอนเงินนี้ไม่สำเร็จ",
    createSuccess: "โอนเงินสำเร็จ",
    createFailed: "โอนเงินไม่สำเร็จ",
    updateSuccess: "แก้ไขรายการโอนเงินสำเร็จ",
    updateFailed: "แก้ไขรายการโอนเงินไม่สำเร็จ",
    deleteSuccess: "ลบรายการโอนเงินสำเร็จ",
    deleteFailed: "ลบรายการโอนเงินไม่สำเร็จ",
    sourceWalletRequired: "กรุณาเลือกกระเป๋าต้นทาง",
    destinationWalletRequired: "กรุณาเลือกกระเป๋าปลายทาง",
    sameWallet: "กระเป๋าต้นทางและปลายทางต้องไม่ใช่ใบเดียวกัน",
    amountRequired: "กรุณากรอกจำนวนเงิน",
    amountInvalid: "จำนวนเงินต้องมากกว่า 0",
    dateRequired: "กรุณาเลือกวันที่โอน",
    futureDate: "วันที่โอนต้องไม่เกินวันนี้",
    sourceWalletNotFound: "ไม่พบกระเป๋าต้นทาง",
    balanceNotEnough: "ยอดเงินในกระเป๋าต้นทางไม่เพียงพอ",
  },
} as const;
